# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 17:21
from __future__ import unicode_literals

import client.lazyjason
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=10240)),
                ('link', models.CharField(max_length=1024, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('db_attrs', models.CharField(default=b'{}', max_length=102400)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, client.lazyjason.LazyJason),
        ),
    ]
