db:
  image: postgres

web:
  build: .
  command: /bin/bash -c "sleep 5 && python manage.py runserver 0.0.0.0:8081"
  volumes:
     # HOST : CONTAINER [: access mode]
    - .:/projects
    - /a/tmp/live_root:/root
  ports:
     # HOST : CONTAINER
    - "8081:8081"
  links:
    - db

celery:
  build: .
  command: /bin/bash -c "sleep 5 && python manage.py celery -A client.tasks worker --loglevel=info"
  volumes:
     # HOST : CONTAINER [: access mode]
    - .:/projects
    - /a/tmp/live_root:/root
  links:
    - db
